
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.60
distribution_type: module
version: 0.01
name: Data-Digest
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  Params::Util: 0.10
  IO::File: 0
  Digest: 1.06
  Digest::SHA: 5.34
  Digest::MD5: 2.33
  IO::Handle: 0
  Carp: 0
abstract: Objects that represent a digest values
